export enum Roles {
  Admin = 'Admin',
  User = 'User',
}

export class User {
  id: string
  role: Roles
  email: string
  password: string

  // Autogenerated by ORM:
  createdAt?: Date
  updatedAt?: Date
}
